tasks:
  - command: |
      yarn
      time yarn build
      yarn start
  - before: |
      time yarn playwright install-deps
      time yarn playwright install
ports:
  - port: 6001
    visibility: public
    onOpen: open-browser
  - port: 6002
    visibility: public
